//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photohosting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int UID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phone_Number { get; set; }
        public Nullable<System.DateTime> BdayDate { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public byte[] Pic { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    }
}
