//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photohosting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desc
    {
        public int DescID { get; set; }
        public string DName { get; set; }
        public string DFileName { get; set; }
        public Nullable<int> UID { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
