//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photohosting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interest
    {
        public int UID { get; set; }
        public string Anime { get; set; }
        public string Recepies { get; set; }
        public string Sports { get; set; }
        public string Movies { get; set; }
        public string Cartoons { get; set; }
        public string Tattoo { get; set; }
        public string Music { get; set; }
        public string Athetics { get; set; }
        public string Traveling { get; set; }
        public string Humor { get; set; }
        public string IT { get; set; }
        public string Psychology { get; set; }
        public string Games { get; set; }
        public string Wallpapers { get; set; }
        public string ExtraFileName { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
