//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photohosting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhotohostingEntities : DbContext
    {
        public PhotohostingEntities()
            : base("name=PhotohostingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Desc> Descs { get; set; }
        public virtual DbSet<Interest> Interests { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
