//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photohosting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public int PID { get; set; }
        public string PicFileName { get; set; }
        public string MainColor { get; set; }
        public string MainTopic { get; set; }
    }
}
